// Generated by https://quicktype.io

export default interface Playlist {
  collaborative: boolean;
  description:   null;
  external_urls: ExternalUrls;
  followers:     Followers;
  href:          string;
  id:            string;
  images:        any[];
  name:          string;
  owner:         Owner;
  primary_color: null;
  public:        boolean;
  snapshot_id:   string;
  tracks:        Tracks;
  type:          string;
  uri:           string;
}

interface ExternalUrls {
  spotify: string;
}

interface Followers {
  href:  null;
  total: number;
}

interface Owner {
  display_name:  string;
  external_urls: ExternalUrls;
  href:          string;
  id:            string;
  type:          string;
  uri:           string;
}

interface Tracks {
  href:     string;
  items:    any[];
  limit:    number;
  next:     null;
  offset:   number;
  previous: null;
  total:    number;
}
