// Generated by https://quicktype.io
export interface AccesToken {
  access_token: string;
  token_type:   string;
  expires_in:   number;
}

export interface AuthToken {
  access_token: string;
  expires_in: number;
  refresh_token: string;
  scope: string;
  token_type: string;
}
